/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Archive.lectureArchive;
import CriticServices.betsVerify;
import Errores.error;
import com.sun.tools.javac.Main;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import objects.Apuesta;

/**
 *
 * @author alexis
 */
public class MainJFrame extends javax.swing.JFrame {

    private Apuesta apuestaTotal;
    private JTextArea areaApuestas;
    private Apuesta[] apuestas;
    private error[] errores;
    // Variables globales

    //  File archivoEntrada = new File();
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Apuestas del hipodromo");

        jLabel2.setText("Ingreso del Archivo de entrada:");

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Generar Analisis");

        jButton3.setText("Generar Analsis Apuestas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Visualizacion del archivo");

        jButton5.setText("Vista Apuestas Exitosas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Vista de Apuestas");

        jLabel6.setText("Agregar Apuesta");

        jButton6.setText("Generar Analsis Apuestas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(647, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(328, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ApuestasAceptadas vistaCalculoResultado = new ApuestasAceptadas(apuestas);

    }//GEN-LAST:event_jButton5ActionPerformed
// ingreso del archivo de texto para el jtextarea
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jTextArea1.setText("");
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // seleccion del archivo seleccionado en el fichero 
            File fichero = fileChooser.getSelectedFile();

            try {
                lectureArchive ingresoArchivo = new lectureArchive();
                ingresoArchivo.cargaArchivo(fichero, jTextArea1);

                for (String texto : ingresoArchivo.obtencionLineas(jTextArea1.getText())) {
                    System.out.println(texto);
                }
                System.out.println(ingresoArchivo.obtencionLineas(jTextArea1.getText()).length);

                for (String texto : ingresoArchivo.generacionDeDatos(jTextArea1.getText())) {
                    System.out.println(texto);
                }
                System.out.println(ingresoArchivo.generacionDeDatos(jTextArea1.getText()).length);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //nuevas apuestas
        NewBet apuestaIngreso = new NewBet(jTextArea1);
        apuestaIngreso.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTextArea1.equals("")) {
            JOptionPane.showMessageDialog(null, "NO EXISTE ARCHIVO INGRESE NUEVAMENTE");
        } else {
            try {
                lectureArchive ingresoArchivo = new lectureArchive();
                int cantidaddeApuestas = this.cantidadApuestas(jTextArea1);
                int numero = 0;
                boolean esVacio = false;
                apuestas = new Apuesta[cantidaddeApuestas];
                String[] cadenass = ingresoArchivo.obtencionLineas(jTextArea1.getText());

                for (int i = 0; i < cadenass.length; i++) {
                    if ((cadenass[i].isBlank()) || cadenass[i].isEmpty()) {
                        JOptionPane.showMessageDialog(null, "ERROR");
                        esVacio = true;
                        break;
                    } else {
                        addBets(cadenass[i], numero, apuestas);
                        numero++;
                    }
                }

                if (esVacio != true) {
                    betsVerify verificacion = new betsVerify();
                    verificacion.verificar(apuestas);

                }
                int prueba = 0;
            

                for (Apuesta ver : apuestas) {
                    System.out.println(prueba + " " + ver.toString() + " ");
                    prueba++;
                }
              
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        lectureArchive ingresoArchivo = new lectureArchive();
        for (String texto : this.ordenApuesta(ingresoArchivo.obtencionLineas(jTextArea1.getText()), cantidadApuestas(jTextArea1))) {
            System.out.println(texto);
        }
        System.out.println(cantidadApuestas(jTextArea1));
    }//GEN-LAST:event_jButton3ActionPerformed
// impresion de los valores
    public String[] ordenApuesta(String[] datos, int cantidad) {
        String[] apuestas = new String[cantidad];
        for (int i = 0; i < cantidad; i++) {
            try {
                apuestas = (datos[i].split(","));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        return apuestas;

    }

    // metodo de ingreso de las apuestas EL CUAL DEBE DE CUMPLIR CON EL O(1)
    public void addBets(String line, int cantidadLineas, Apuesta[] apuetas) {

        String[] datosStringOrden = line.split(",");
        int[] orden = new int[10];
        Apuesta nuevaApuesta = new Apuesta();
        try {

            String nombre = datosStringOrden[0];
            double monto = Double.parseDouble(datosStringOrden[1]);
            // ahora el ingreso del orden
            for (int i = 0; i < 10; i++) {
                orden[i] = Integer.parseInt(datosStringOrden[i + 2]);
            }
            nuevaApuesta.setNombre(nombre);
            nuevaApuesta.setMonto(monto);
            nuevaApuesta.setApuestaCaballosOrden(orden);
            nuevaApuesta.setValida(true);
        } catch (Exception e) {
            e.printStackTrace();
            nuevaApuesta.setValida(false);

        }
        apuetas[cantidadLineas] = nuevaApuesta;

    }

    // metodo para ver la cantidad de lineas, las cuales 
    // en este caso figuran como la cantidad de apuestas
    public int cantidadApuestas(JTextArea textArea) {
        int cantidad = 0;
        textArea.setCaretPosition(0);
        cantidad = textArea.getLineCount() - 1;
        return cantidad;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
